""" gvimrc

scriptencoding utf-8

let $MYGVIMRC = resolve($MYGVIMRC)

augroup gvimrc
  autocmd!
  autocmd GUIEnter * call OnGuiEnter()
  autocmd InsertLeave * :set iminsert=0
augroup END

function! OnGuiEnter()
  set columns=120 lines=35
  winpos 560 420
endfunction

augroup gvimrc-initial-directory
  autocmd!
  "autocmd GUIEnter * if argc() == 0 && getcwd() == $VIM | execute 'silent! cd c:\work' | endif
  autocmd GUIEnter * if argc() == 0 && getcwd() == $VIM | execute 'silent! cd $HOME' | endif
augroup END

"set guifont=Consolas:h11 guifontwide=Ricty_Diminished:h11
"set renderoptions=type:directx,renmode:5
"set guifont=Consolas:h11 guifontwide=Myrica_M:h11
"set renderoptions=type:directx,renmode:0

"set guifont=BDF_UM+:h9 guifontwide=BDF_UM+:h9 renderoptions=

"set guifont=VL_Gothic:h9 guifontwide=VL_Gothic:h9 "rop=type:directx,renmode:4
"set renderoptions=type:directx,renmode:5

set guifont=Go_Mono:h10 guifontwide=BIZ_UD明朝_Medium:h11 linespace=4 rop=type:directx,renmode:5

command! FontSizeNormal :set gfn=Go_Mono:h9  gfw=BIZ_UD明朝_Medium:h10
"command! FontSizeLarge  :set gfn=Go_Mono:h10 gfw=BIZ_UD明朝_Medium:h11
command! -nargs=? FontSizeLarge
      \ :exe printf('set gfn=Go_Mono:h%d gfw=BIZ_UD明朝_Medium:h%d', 10+abs(<q-args>), 11+abs(<q-args>))

let s:python_env = ''
if $VIRTUAL_ENV != ''
  let s:venv = fnamemodify($VIRTUAL_ENV, ':t')
  let s:python_version = trim(system("python -c \"import sys; v=sys.version_info; print(f'{v.major}.{v.minor}.{v.micro}')\""))
  let s:python_env = '(' . s:venv . '/' . s:python_version . ') '
endif
"let &titlestring = "%t%(\ %M%) \u2329%{fnamemodify(expand('%:p:~:.:h'), ':gs?\\?/?')}/\u232A %<| %{fnamemodify(getcwd(), ':~:gs?\\?/?')}/ - Vim"
let &titlestring = s:python_env . "%t%(\ %M%) \u2329%{fnamemodify(@%, ':p:~:.:h:gs?\\?/?')}/\u232A %<| %{fnamemodify(getcwd(), ':~:gs?\\?/?')}/ - Vim"

set guioptions-=T guioptions-=m guioptions-=r guioptions-=L guioptions-=e
set guioptions+=c

let g:lucius_style = 'light'
let g:lucius_contrast = 'low'
let g:lucius_contrast_bg = 'normal'
"colorscheme lucius

let g:tokyonight_style = 'storm'
let g:tokyonight_disable_italic_comment = 1
let g:tokyonight_menu_selection_background = 'blue'
let g:tokyonight_cursor = 'red'
"colorscheme tokyonight

set background=light
colorscheme iceberg
silent! let g:lightline.colorscheme = 'iceberg'
silent! exe 'call lightline#init() | call lightline#colorscheme() | call lightline#update()'

set visualbell& errorbells&
if 0
  let &t_vb = "\<Esc>|100f"
  set visualbell errorbells belloff=esc
endif

"set guicursor& guicursor+=a:blinkon0
set guicursor& guicursor+=a:blinkwait550-blinkon550-blinkoff550

"command! Diff2  browse tabedit | browse vsplit | windo diffthis
"command! Diff3  browse tabedit | browse vsplit | browse vsplit | windo diffthis

nnoremap <C-Tab>    gt
nnoremap <C-S-Tab>  gT

let s:gvimrclocal = $MYGVIMRC.'_local'
if filereadable(s:gvimrclocal)
  execute 'source' s:gvimrclocal
endif

""" vim: set et ts=2 sts=2 sw=2:
""" gvimrc ends here
